export const items = [
  {
    id: "w39mk3",
    name: "Polo manga larga estampada única",
    image: "w39mk3",
    colours: 2,
    basePrice: 18.99,
    discount: 20,
    currency: "€",
  },
  {
    id: "3ikmnr",
    name: "Polo manga larga bandas tricolor",
    image: "3ikmnr",
    colours: 3,
    basePrice: 20.99,
    discount: 0,
    currency: "€",
  },
  {
    id: "fn3133",
    name: "Polo manga larga estampada",
    image: "fn3133",
    colours: 3,
    basePrice: 18.99,
    discount: 20,
    currency: "€",
  },
  {
    id: "adm934",
    name: "Polo manga larga miniestampas",
    image: "adm934",
    colours: 1,
    basePrice: 16.99,
    discount: 0,
    currency: "€",
  },
  {
    id: "ansfg9",
    name: "Polo manga larga estampada",
    image: "ansfg9",
    colours: 3,
    basePrice: 18.99,
    discount: 20,
    currency: "€",
  },
  {
    id: "bhhui1",
    name: "Polo manga larga estampada",
    image: "bhhui1",
    colours: 2,
    basePrice: 18.99,
    discount: 20,
    currency: "€",
  },
  {
    id: "pxkne7",
    name: "Polo manga larga bandas tricolor",
    image: "pxkne7",
    colours: 3,
    basePrice: 20.99,
    discount: 0,
    currency: "€",
  },
  {
    id: "mn3nx8",
    name: "Polo manga larga estampada",
    image: "mn3nx8",
    colours: 3,
    basePrice: 18.99,
    discount: 20,
    currency: "€",
  },
];
